import type { MotionSkill, MotionCategory } from '@/motion/core/types';

/**
 * THE SKILL REGISTRY.
 *
 * One entry per reusable behaviour in the system. The showcase reads this file
 * to build its documentation cards and its inspector, so a skill that is not
 * registered here is invisible — deliberately. Adding a skill and registering
 * it are the same task.
 *
 * `sourceReference` quotes the reference brief verbatim; MOTION-SOURCE-MAP.md
 * is generated from these strings, so keep them exact.
 */
export const motionSkills: MotionSkill[] = [
  /* ── A · LOAD & TRANSITIONS ─────────────────────────────────────────── */
  {
    id: 'cinematic-loader',
    name: 'Cinematic Loader',
    category: 'load',
    description: 'Full-screen entrance overlay with a shimmering mark and an eased exit.',
    sourceReference: 'Loading screen (3s monogram shimmer, ease-out fade)',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['gsap', 'react', 'css'],
    desktop: 'Full 3s hold, shimmering monogram, 0.9s eased exit that lifts the mark as the veil drops.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Same timing, but the hold is the first thing to cut if LCP is tight.' },
    reducedMotion: { behaviour: 'disabled', note: 'Removed entirely, hold included. Asking for less motion is not asking to wait longer for it.' },
    recommendedUse: ['Agency and portfolio sites', 'Campaign microsites', 'Anywhere the first frame sets a tone'],
    export: 'CinematicLoader',
    usage: '<CinematicLoader duration={3} logo="MS" skipOnRepeatVisit />',
  },
  {
    id: 'page-reveal',
    name: 'Page Reveal',
    category: 'load',
    description: 'The page entrance that follows the loader out: a short rise and fade.',
    sourceReference: 'then ease-out fade',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['gsap', 'react'],
    desktop: '14px rise over 1s, starting as the loader clears.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Opacity and transform only, so it is free everywhere.' },
    reducedMotion: { behaviour: 'static', note: 'Content is placed, not animated.' },
    recommendedUse: ['Every page that uses the loader', 'Route transitions'],
    export: 'PageReveal',
    usage: '<PageReveal delay={0.3}>{children}</PageReveal>',
  },

  /* ── B · HERO & CINEMATIC ───────────────────────────────────────────── */
  {
    id: 'cinematic-hero',
    name: 'Cinematic Hero',
    category: 'hero',
    description: 'Full-viewport hero composing background media, overlay, glow, particles, vignette and grain in a fixed layer order.',
    sourceReference: 'Hero section (full-bleed HLS video bg, centered headline) · Hero takes 100svh',
    difficulty: 'intermediate',
    performanceCost: 'medium',
    dependencies: ['react', 'css', 'canvas', 'hls.js'],
    desktop: 'All layers active over a playing video.',
    tablet: 'All layers, reduced particle count.',
    mobile: { behaviour: 'simplified', note: 'Poster instead of video, a third of the particles. Sized in svh so the CTA is not hidden under the address bar on arrival.' },
    reducedMotion: { behaviour: 'static', note: 'Poster frame, no particles, no glow pulse. The composition survives.' },
    recommendedUse: ['Agency landing pages', 'Product launches', 'Brand campaign sites'],
    export: 'CinematicHero',
    usage: '<CinematicHero media={{ sources }} particles grain glow>{...}</CinematicHero>',
  },
  {
    id: 'background-video',
    name: 'Background Video (HLS)',
    category: 'hero',
    description: 'Autoplaying muted background video with an HLS path, progressive fallbacks and three separate still-image fallbacks.',
    sourceReference: 'Background: hls.js video with 50% black overlay',
    difficulty: 'advanced',
    performanceCost: 'high',
    dependencies: ['hls.js', 'react'],
    desktop: 'hls.js where needed; native HLS in Safari, where loading the library too would mean two players fighting over one element.',
    tablet: 'Identical, capped to the player size.',
    mobile: { behaviour: 'static', note: 'Poster when posterOnMobile is set. Also falls back to the poster on Save-Data and 2G, for different reasons than the phone case.' },
    reducedMotion: { behaviour: 'static', note: 'Poster frame. Motion nobody asked for is exactly what the setting means.' },
    recommendedUse: ['Hero backgrounds', 'Ambient section backdrops', 'Showreels'],
    export: 'HlsVideo',
    usage: '<HlsVideo src="/stream.m3u8" sources={[...]} poster="/poster.jpg" pauseOffscreen />',
  },
  {
    id: 'media-overlay',
    name: 'Media Overlay',
    category: 'hero',
    description: 'Configurable wash over media — flat, directional or radial — that makes overlaid text legible.',
    sourceReference: '50% black overlay',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['css'],
    desktop: 'Directional gradient by default: darkens the band the copy sits on and leaves the rest of the image alive.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Often needs more opacity: less screen means text sits over busier parts of the frame.' },
    reducedMotion: { behaviour: 'identical', note: 'Static by nature.' },
    recommendedUse: ['Any text over media', 'Hero legibility', 'Card image scrims'],
    export: 'MediaOverlay',
    usage: '<MediaOverlay opacity={0.5} gradient="to-bottom" />',
  },
  {
    id: 'ambient-particles',
    name: 'Ambient Particles (Dust)',
    category: 'hero',
    description: 'Canvas dust motes drifting upward, each breathing at its own rate.',
    sourceReference: 'Subtle dust particle layer on top',
    difficulty: 'intermediate',
    performanceCost: 'medium',
    dependencies: ['canvas', 'react'],
    desktop: '~46 motes on one canvas layer. The loop stops the moment the layer leaves the viewport.',
    tablet: 'Same, fewer motes.',
    mobile: { behaviour: 'simplified', note: 'A third of the count, or removed outright with disableOnMobile.' },
    reducedMotion: { behaviour: 'disabled', note: 'Nothing rendered; the canvas is not even mounted.' },
    recommendedUse: ['Cinematic heroes', 'Dark atmospheric sections'],
    export: 'DustParticles',
    usage: '<DustParticles count={46} disableOnMobile />',
  },

  /* ── C · TEXT ───────────────────────────────────────────────────────── */
  {
    id: 'text-reveal',
    name: 'Text Reveal',
    category: 'text',
    description: 'Headline that rises into view by line, word, character or as a whole.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals · Headline mixing sans + italic serif',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Lines rise out of an overflow mask, staggered, after document.fonts.ready.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Word or element mode: a long headline split into many lines on a narrow screen staggers for too long.' },
    reducedMotion: { behaviour: 'static', note: 'No split at all, which also leaves the accessibility tree untouched.' },
    recommendedUse: ['Hero headlines', 'Section openers', 'Pull quotes'],
    export: 'TextReveal',
    usage: '<TextReveal by="lines" stagger={0.08}>Your headline</TextReveal>',
  },
  {
    id: 'split-text-reveal',
    name: 'Split Text Reveal',
    category: 'text',
    description: 'The splitter underneath Text Reveal: cuts text into spans while preserving the accessible label.',
    sourceReference: 'Headline mixing sans + italic serif',
    difficulty: 'advanced',
    performanceCost: 'low',
    dependencies: ['gsap'],
    desktop: 'Char, word or line splitting, measured after fonts are ready.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Character splitting is avoided: dozens of inline-block spans per headline cost layout for little visible gain.' },
    reducedMotion: { behaviour: 'disabled', note: 'Not invoked.' },
    recommendedUse: ['Cinematic headlines', 'Kinetic typography'],
    export: 'splitText',
    usage: 'const { parts, revert } = splitText(el, "lines")',
  },
  {
    id: 'fade-up',
    name: 'Fade Up',
    category: 'text',
    description: 'The workhorse entrance: opacity plus a short directional rise.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: '36px rise, 0.8s, power3.out.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Distance drops to ~16px: a long travel on a short viewport arrives late.' },
    reducedMotion: { behaviour: 'static', note: 'Visible immediately; no trigger created.' },
    recommendedUse: ['Almost anything', 'The default when unsure'],
    export: 'FadeUp',
    usage: '<FadeUp distance={36}>{children}</FadeUp>',
  },
  {
    id: 'fade-scale',
    name: 'Fade + Scale',
    category: 'text',
    description: 'Entrance that settles from 0.94 to 1 while fading in.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Scale 0.94 to 1 with opacity.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Transform and opacity only.' },
    reducedMotion: { behaviour: 'static', note: 'Placed at final scale.' },
    recommendedUse: ['Media blocks', 'Cards', 'Logos'],
    export: 'FadeScale',
    usage: '<FadeScale>{children}</FadeScale>',
  },
  {
    id: 'stagger-reveal',
    name: 'Stagger Reveal',
    category: 'text',
    description: 'Children animate in sequence from one trigger.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'basic',
    performanceCost: 'low',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: '0.08s between children, in DOM order.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Tighter step: on a single column a 12-item stagger at 0.08s takes a full second to finish.' },
    reducedMotion: { behaviour: 'static', note: 'All children visible at once.' },
    recommendedUse: ['Lists', 'Feature grids', 'Navigation'],
    export: 'StaggerReveal',
    usage: '<StaggerReveal stagger={0.08}>{items}</StaggerReveal>',
  },
  {
    id: 'clip-reveal',
    name: 'Clip Reveal',
    category: 'text',
    description: 'Content wiped into view with an animated clip-path.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['gsap', 'scrolltrigger', 'css'],
    desktop: 'Vertical, horizontal or centre wipe.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'clip-path animates on the compositor; no repaint.' },
    reducedMotion: { behaviour: 'static', note: 'Clip removed, content shown.' },
    recommendedUse: ['Images', 'Editorial dividers', 'Full-bleed panel reveals'],
    export: 'ClipReveal',
    usage: '<ClipReveal clipFrom="bottom">{children}</ClipReveal>',
  },

  /* ── D · SCROLL ─────────────────────────────────────────────────────── */
  {
    id: 'scroll-reveal-engine',
    name: 'Scroll Reveal Engine',
    category: 'scroll',
    description: 'The single ScrollTrigger abstraction every reveal goes through: cleanup, initial state, reduced motion and dev markers handled once.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'advanced',
    performanceCost: 'low',
    dependencies: ['gsap', 'scrolltrigger', 'react'],
    desktop: 'Triggers scoped to a container and reverted on unmount by useGSAP.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'ignoreMobileResize is set globally so URL-bar collapse does not refresh every trigger.' },
    reducedMotion: { behaviour: 'disabled', note: 'No trigger created; targets are made visible.' },
    recommendedUse: ['The foundation of every other scroll skill'],
    export: 'useScrollReveal',
    usage: 'const ref = useScrollReveal({ kind: "fade-up", children: ":scope > *" })',
  },
  {
    id: 'parallax',
    name: 'Parallax',
    category: 'scroll',
    description: 'Moves an element at a different rate from the page, expressed relative to its own size.',
    sourceReference: 'Mobile: disable parallax, simplify hover states',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Travel is a fraction of the element size, so one value works at every breakpoint.',
    tablet: 'Reduced speed.',
    mobile: { behaviour: 'disabled', note: 'Off by default. Short scrolls and a finger on the glass turn parallax into lag.' },
    reducedMotion: { behaviour: 'disabled', note: 'No tween created.' },
    recommendedUse: ['Hero imagery', 'Editorial sections', 'Layered backgrounds'],
    export: 'useParallax',
    usage: 'const ref = useParallax({ speed: 0.18 })',
  },
  {
    id: 'sticky-story',
    name: 'Sticky Storytelling',
    category: 'scroll',
    description: 'Pinned section that steps through chapters, driving text and visuals from one progress value.',
    sourceReference: 'Sticky-pinned scroll variant on desktop',
    difficulty: 'advanced',
    performanceCost: 'medium',
    dependencies: ['gsap', 'scrolltrigger', 'react'],
    desktop: 'The section pins and chapters cross-fade in place with a progress rail.',
    tablet: 'Pinned, shorter scroll per chapter.',
    mobile: { behaviour: 'simplified', note: 'A different layout, not a smaller one: chapters stack and scroll normally, because pinning fights the URL bar on a phone.' },
    reducedMotion: { behaviour: 'simplified', note: 'Falls back to the stacked layout.' },
    recommendedUse: ['Process and method sections', 'Case studies', 'Feature walkthroughs'],
    export: 'StickyStory',
    usage: '<StickyStory chapters={chapters} heightPerStep={1} />',
  },
  {
    id: 'horizontal-scroll',
    name: 'Horizontal Scroll',
    category: 'scroll',
    description: 'Vertical scrolling drives a horizontal track across a pinned section.',
    sourceReference: 'Sticky-pinned scroll variant on desktop',
    difficulty: 'advanced',
    performanceCost: 'medium',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Pin distance computed from the real track width and recomputed on refresh.',
    tablet: 'Same, shorter track.',
    mobile: { behaviour: 'simplified', note: 'Native swipe strip with scroll-snap and overscroll containment, so swiping past the end does not trigger the back gesture.' },
    reducedMotion: { behaviour: 'simplified', note: 'Native strip.' },
    recommendedUse: ['Portfolio galleries', 'Timelines', 'Product ranges'],
    export: 'HorizontalScrollSection',
    usage: '<HorizontalScrollSection>{cards}</HorizontalScrollSection>',
  },
  {
    id: 'scroll-scrub-media',
    name: 'Scroll-Scrub Media',
    category: 'scroll',
    description: 'Video or image sequence whose frame is chosen by scroll position.',
    sourceReference: 'Sticky-pinned scroll variant on desktop',
    difficulty: 'advanced',
    performanceCost: 'high',
    dependencies: ['gsap', 'scrolltrigger', 'canvas'],
    desktop: 'Seeks inside requestAnimationFrame, never faster than the decoder can deliver.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Shorter clips or fewer frames. Needs a server answering HTTP Range, or it will not seek at all.' },
    reducedMotion: { behaviour: 'static', note: 'First frame held.' },
    recommendedUse: ['Product reveals', 'Before and after transformations', 'Assembly and process films'],
    export: 'useScrollScrubVideo',
    usage: 'const { containerRef, videoRef } = useScrollScrubVideo()',
  },

  /* ── E · PRODUCT ────────────────────────────────────────────────────── */
  {
    id: 'product-scroll',
    name: 'Product Scroll',
    category: 'product',
    description: 'Pinned product stage with synchronised chapters and hotspots, over a video, an image sequence or a canvas renderer.',
    sourceReference: 'Sticky-pinned scroll variant on desktop · scroll-controlled',
    difficulty: 'advanced',
    performanceCost: 'high',
    dependencies: ['gsap', 'scrolltrigger', 'canvas', 'hls.js', 'react'],
    desktop: 'Three interchangeable sources behind one API; chapters, hotspots and the progress rail all read the same value.',
    tablet: 'Pinned with a shorter scroll length.',
    mobile: { behaviour: 'simplified', note: 'Takes a stacked fallback layout. A product shot at 375px wide with a caption over it is unreadable.' },
    reducedMotion: { behaviour: 'simplified', note: 'Stacked fallback; first frame only.' },
    recommendedUse: ['Product storytelling', 'Hardware and industrial sites', '3D render showcases'],
    export: 'ProductScroll',
    usage: '<ProductScroll source={{ type: "canvas", render }} chapters={...} hotspots={...} />',
  },

  /* ── F · CARDS ──────────────────────────────────────────────────────── */
  {
    id: 'card-hover-lift',
    name: 'Card Hover Lift',
    category: 'cards',
    description: 'Card rises toward the viewer on hover.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['framer-motion'],
    desktop: '6px rise over 300ms.',
    tablet: 'Identical where a pointer exists.',
    mobile: { behaviour: 'disabled', note: 'No listener attached. A hover that fires on tap makes the card look broken in the moment before navigation.' },
    reducedMotion: { behaviour: 'disabled', note: 'Colour feedback only.' },
    recommendedUse: ['Bento grids', 'Case study cards', 'Pricing tables'],
    export: 'HoverCard',
    usage: '<HoverCard lift={6}>{content}</HoverCard>',
  },
  {
    id: 'card-scale',
    name: 'Card Scale',
    category: 'cards',
    description: 'Subtle scale on hover, composable with lift.',
    sourceReference: 'button slight scale (1.02)',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['framer-motion'],
    desktop: '1.01 to 1.03. Beyond that it reads as a different card rather than the same one responding.',
    tablet: 'Identical.',
    mobile: { behaviour: 'disabled', note: 'No hover state exists.' },
    reducedMotion: { behaviour: 'disabled', note: 'Off.' },
    recommendedUse: ['Feature cards', 'Media tiles'],
    export: 'HoverCard',
    usage: '<HoverCard scale={1.02} lift={0} />',
  },
  {
    id: 'image-zoom',
    name: 'Image Zoom',
    category: 'cards',
    description: 'Image scales inside a fixed frame while the frame stays put.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['framer-motion', 'css'],
    desktop: '1.06 over 700ms inside an overflow-hidden frame.',
    tablet: 'Identical.',
    mobile: { behaviour: 'disabled', note: 'No hover state exists.' },
    reducedMotion: { behaviour: 'disabled', note: 'Static image.' },
    recommendedUse: ['Portfolio thumbnails', 'Editorial cards', 'Product tiles'],
    export: 'ZoomImage',
    usage: '<ZoomImage src="/shot.jpg" scale={1.06} />',
  },
  {
    id: 'glass-card',
    name: 'Glass Card',
    category: 'cards',
    description: 'Translucent blurred surface with a hairline border and an upper-lip highlight.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'basic',
    performanceCost: 'medium',
    dependencies: ['css'],
    desktop: 'backdrop-filter blur with saturation, plus the top-edge highlight that makes it read as glass.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Reduce the blur radius. backdrop-filter is the single most expensive property in this library on mobile GPUs.' },
    reducedMotion: { behaviour: 'identical', note: 'Static surface.' },
    recommendedUse: ['Cards over imagery', 'Floating panels', 'Navigation bars'],
    export: 'GlassCard',
    usage: '<GlassCard radius={16}>{content}</GlassCard>',
  },
  {
    id: 'bento-grid-motion',
    name: 'Bento Grid Motion',
    category: 'cards',
    description: 'Staggered entrance for an asymmetric grid, ordered by DOM position.',
    sourceReference: '8 cards in an asymmetric grid',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Cards rise in reading order, 0.07s apart.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'The grid collapses to one column, where DOM and visual order already agree.' },
    reducedMotion: { behaviour: 'static', note: 'All cards visible.' },
    recommendedUse: ['Feature grids', 'Service overviews', 'Dashboards'],
    export: 'BentoGrid',
    usage: '<BentoGrid stagger={0.07}>{cards}</BentoGrid>',
  },

  /* ── G · MICROINTERACTIONS ──────────────────────────────────────────── */
  {
    id: 'button-scale',
    name: 'Button Scale',
    category: 'interaction',
    description: 'Hover and press feedback at 1.02 and 0.98.',
    sourceReference: 'button slight scale (1.02)',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['framer-motion'],
    desktop: '1.02 on hover, 0.98 on press, 200ms.',
    tablet: 'Press state only.',
    mobile: { behaviour: 'simplified', note: 'Press feedback survives; hover does not exist.' },
    reducedMotion: { behaviour: 'disabled', note: 'Colour transition only.' },
    recommendedUse: ['Every button in the system'],
    export: 'MagneticButton',
    usage: '<MagneticButton variant="solid">Start</MagneticButton>',
  },
  {
    id: 'magnetic-button',
    name: 'Magnetic Button',
    category: 'interaction',
    description: 'Button leans toward the cursor inside a radius and springs back on leave.',
    sourceReference: 'Hover: card lift, button slight scale (1.02)',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['gsap', 'framer-motion'],
    desktop: 'Element-scoped pointer listener and gsap.quickTo, so a moving cursor retargets one live tween instead of spawning one per event.',
    tablet: 'Disabled unless a fine pointer is present.',
    mobile: { behaviour: 'disabled', note: 'No listener is attached at all. There is no cursor to be attracted to.' },
    reducedMotion: { behaviour: 'disabled', note: 'Plain button.' },
    recommendedUse: ['Primary CTAs', 'Hero actions'],
    export: 'MagneticButton',
    usage: '<MagneticButton strength={0.35} radius={60}>Talk to us</MagneticButton>',
  },
  {
    id: 'magnetic-link',
    name: 'Magnetic Link',
    category: 'interaction',
    description: 'Weaker magnetic pull for inline links, with no scale.',
    sourceReference: 'Hover: card lift, button slight scale (1.02)',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['gsap'],
    desktop: '0.22 strength, 34px radius, no scale: a link that grows competes with its own paragraph.',
    tablet: 'Disabled on coarse pointers.',
    mobile: { behaviour: 'disabled', note: 'Plain link.' },
    reducedMotion: { behaviour: 'disabled', note: 'Plain link.' },
    recommendedUse: ['Footer navigation', 'Inline emphasis', 'Menu items'],
    export: 'MagneticLink',
    usage: '<MagneticLink href="/work">Selected work</MagneticLink>',
  },
  {
    id: 'hover-glow',
    name: 'Hover Glow',
    category: 'interaction',
    description: 'Radial highlight that tracks the cursor across a surface.',
    sourceReference: 'Background: subtle radial lime glow at bottom-center',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['css', 'react'],
    desktop: 'Two CSS custom properties feed one static gradient, so no gradient is reparsed per pointer event.',
    tablet: 'Static centred glow.',
    mobile: { behaviour: 'simplified', note: 'Static centred glow at half intensity, so the surface still reads as lit.' },
    reducedMotion: { behaviour: 'simplified', note: 'Static centred glow.' },
    recommendedUse: ['Cards', 'Panels', 'CTA surfaces'],
    export: 'useHoverGlow',
    usage: 'const ref = useHoverGlow({ size: 320 })',
  },
  {
    id: 'image-tilt',
    name: 'Image Tilt',
    category: 'interaction',
    description: '3D lean toward the cursor, capped at about 7 degrees.',
    sourceReference: 'Hover: card lift, button slight scale (1.02)',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['gsap'],
    desktop: 'Y follows horizontal position and X inverts vertical, which is what makes the surface feel pushed rather than steered.',
    tablet: 'Disabled on coarse pointers.',
    mobile: { behaviour: 'disabled', note: 'No listener attached.' },
    reducedMotion: { behaviour: 'disabled', note: 'Flat surface.' },
    recommendedUse: ['Feature cards', 'Product thumbnails', 'Team portraits'],
    export: 'useTilt',
    usage: 'const ref = useTilt({ max: 7 })',
  },

  /* ── H · MARQUEE ────────────────────────────────────────────────────── */
  {
    id: 'infinite-marquee',
    name: 'Infinite Marquee',
    category: 'marquee',
    description: 'Seamless looping strip in CSS, pausing on hover.',
    sourceReference: 'Marquee: CSS infinite scroll, pauses on hover · BUILT WITH AI · NOT BY AI ·',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['css', 'react'],
    desktop: 'Track duplicated exactly once and translated -50%; the duplicate is aria-hidden so the strip is read once.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Composited off the main thread, so it is one of the few effects that costs nothing on a phone.' },
    reducedMotion: { behaviour: 'static', note: 'Becomes a normal scrollable strip. The words were the point; the movement was decoration.' },
    recommendedUse: ['Client logos', 'Statement strips', 'Service lists'],
    export: 'Marquee',
    usage: '<Marquee speed={26} reverse pauseOnHover>{items}</Marquee>',
  },

  /* ── I · UI MOTION ──────────────────────────────────────────────────── */
  {
    id: 'animated-accordion',
    name: 'Animated Accordion',
    category: 'ui',
    description: 'Height and opacity panel transition with full keyboard and ARIA support.',
    sourceReference: 'FAQ accordion · Smooth height + opacity transition (300ms ease-out)',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['framer-motion', 'react'],
    desktop: '300ms height-from-auto, single or multiple open modes.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Same behaviour, larger tap targets.' },
    reducedMotion: { behaviour: 'simplified', note: 'Instant open and close; the state change is still visible.' },
    recommendedUse: ['FAQ', 'Specifications', 'Progressive disclosure'],
    export: 'Accordion',
    usage: '<Accordion items={faq} mode="single" />',
  },

  /* ── J · SECTION TRANSITIONS ────────────────────────────────────────── */
  {
    id: 'fade-section-transition',
    name: 'Fade Section Transition',
    category: 'transition',
    description: 'Section fades in as it enters.',
    sourceReference: 'then ease-out fade',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: '1.2s opacity.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Opacity only.' },
    reducedMotion: { behaviour: 'static', note: 'Visible immediately.' },
    recommendedUse: ['The default section entrance'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="fade">{section}</SectionTransition>',
  },
  {
    id: 'scale-section-transition',
    name: 'Scale Section Transition',
    category: 'transition',
    description: 'Section settles from 1.06 to 1.',
    sourceReference: 'then ease-out fade',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Scale with opacity.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Transform only.' },
    reducedMotion: { behaviour: 'static', note: 'Placed at final scale.' },
    recommendedUse: ['Media-led sections', 'Full-bleed panels'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="scale" />',
  },
  {
    id: 'clip-section-transition',
    name: 'Clip Section Transition',
    category: 'transition',
    description: 'Section unmasks from a rounded inset to full bleed.',
    sourceReference: 'then ease-out fade',
    difficulty: 'intermediate',
    performanceCost: 'low',
    dependencies: ['gsap', 'scrolltrigger', 'css'],
    desktop: 'clip-path inset with an animated corner radius.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Composited.' },
    reducedMotion: { behaviour: 'static', note: 'Clip removed.' },
    recommendedUse: ['Hero-to-content handoffs', 'Chapter breaks'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="clip" />',
  },
  {
    id: 'blur-transition',
    name: 'Blur Transition',
    category: 'transition',
    description: 'Section resolves from blurred to sharp.',
    sourceReference: 'then ease-out fade',
    difficulty: 'intermediate',
    performanceCost: 'high',
    dependencies: ['gsap', 'scrolltrigger', 'css'],
    desktop: '14px to 0 blur.',
    tablet: 'Reduced radius.',
    mobile: { behaviour: 'simplified', note: 'Prefer fade. filter: blur repaints the whole subtree every frame, which is fine as a short entrance and costly when scrubbed.' },
    reducedMotion: { behaviour: 'static', note: 'Sharp immediately.' },
    recommendedUse: ['A single hero handoff', 'Sparingly'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="blur" />',
  },
  {
    id: 'cinematic-section-transition',
    name: 'Cinematic Section Transition',
    category: 'transition',
    description: 'Clip, scale and blur composed into one signature entrance.',
    sourceReference: 'then ease-out fade',
    difficulty: 'advanced',
    performanceCost: 'high',
    dependencies: ['gsap', 'scrolltrigger', 'css'],
    desktop: '1.6s, expo.out, three properties at once.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Drops the blur channel.' },
    reducedMotion: { behaviour: 'static', note: 'Content placed.' },
    recommendedUse: ['One moment per page: the point where the story turns'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="cinematic" />',
  },

  /* ── K · ATMOSPHERE ─────────────────────────────────────────────────── */
  {
    id: 'grain',
    name: 'Grain / Noise',
    category: 'atmosphere',
    description: 'Film-like texture over the interface, stepped rather than smooth.',
    sourceReference: 'Subtle dust particle layer on top',
    difficulty: 'basic',
    performanceCost: 'low',
    dependencies: ['css'],
    desktop: 'Inline SVG feTurbulence tile, rasterised once and repeated.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Drop the animation, keep the texture.' },
    reducedMotion: { behaviour: 'static', note: 'Texture without the shimmer.' },
    recommendedUse: ['Dark interfaces', 'Cinematic heroes', 'Photography-led sites'],
    export: 'Grain',
    usage: '<Grain opacity={0.045} animated />',
  },
  {
    id: 'radial-glow',
    name: 'Radial Glow',
    category: 'atmosphere',
    description: 'Coloured light bloom anchored anywhere in a section.',
    sourceReference: 'Background: subtle radial lime glow at bottom-center',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['css'],
    desktop: 'Position, size, colour and intensity configurable, with an optional 9s breathing pulse.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'A gradient costs nothing.' },
    reducedMotion: { behaviour: 'static', note: 'Pulse removed; the glow stays.' },
    recommendedUse: ['Hero backgrounds', 'CTA sections', 'Accent anchoring'],
    export: 'RadialGlow',
    usage: '<RadialGlow x="50%" y="100%" color="rgba(200,242,74,0.3)" animated />',
  },
  {
    id: 'vignette',
    name: 'Vignette',
    category: 'atmosphere',
    description: 'Edge darkening that settles the eye on the centre.',
    sourceReference: '50% black overlay',
    difficulty: 'basic',
    performanceCost: 'none',
    dependencies: ['css'],
    desktop: 'Elliptical gradient with configurable intensity and spread.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Free.' },
    reducedMotion: { behaviour: 'identical', note: 'Static.' },
    recommendedUse: ['Over video', 'Full-bleed imagery', 'Cinematic framing'],
    export: 'Vignette',
    usage: '<Vignette intensity={0.55} spread={0.55} />',
  },
  {
    id: 'light-sweep',
    name: 'Light Sweep',
    category: 'atmosphere',
    description: 'Specular band travelling across a surface, on hover or on a loop.',
    sourceReference: 'Loading screen (3s monogram shimmer, ease-out fade)',
    difficulty: 'basic',
    performanceCost: 'low',
    dependencies: ['css'],
    desktop: 'Transform on a gradient: composite only, no repaint.',
    tablet: 'Identical.',
    mobile: { behaviour: 'simplified', note: 'Hover mode never fires; use loop mode or omit it.' },
    reducedMotion: { behaviour: 'disabled', note: 'Renders nothing.' },
    recommendedUse: ['Buttons', 'Cards', 'Logo marks'],
    export: 'LightSweep',
    usage: '<LightSweep onHover speed={3.2} />',
  },
  {
    id: 'ambient-blur',
    name: 'Ambient Blur',
    category: 'atmosphere',
    description: 'Frosted plane over whatever sits behind it.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'basic',
    performanceCost: 'high',
    dependencies: ['css'],
    desktop: 'backdrop-filter blur and saturation with a tint.',
    tablet: 'Reduced radius.',
    mobile: { behaviour: 'simplified', note: 'Halve the radius or replace it with a solid tint. This is the most expensive property in the library.' },
    reducedMotion: { behaviour: 'identical', note: 'Static.' },
    recommendedUse: ['Sticky navigation', 'Modal backdrops', 'Overlay panels'],
    export: 'AmbientBlur',
    usage: '<AmbientBlur blur={24} tint="rgba(8,9,10,0.45)" />',
  },
  {
    id: 'gradient-border',
    name: 'Gradient Border',
    category: 'atmosphere',
    description: 'Gradient hairline around a surface, masked so glass behind it survives.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'intermediate',
    performanceCost: 'none',
    dependencies: ['css'],
    desktop: 'mask-composite: exclude paints only the ring, leaving any backdrop-filter underneath intact.',
    tablet: 'Identical.',
    mobile: { behaviour: 'identical', note: 'Free.' },
    reducedMotion: { behaviour: 'identical', note: 'Static.' },
    recommendedUse: ['Featured cards', 'Pricing highlights', 'Active states'],
    export: 'GradientBorder',
    usage: '<GradientBorder radius={16}>{content}</GradientBorder>',
  },
];

export const skillsById = Object.fromEntries(motionSkills.map((s) => [s.id, s])) as Record<string, MotionSkill>;

export const categoryLabels: Record<MotionCategory, string> = {
  load: 'Load & Transitions',
  hero: 'Hero & Cinematic',
  text: 'Text Motion',
  scroll: 'Scroll Motion',
  product: 'Product Experience',
  cards: 'Cards & Bento',
  interaction: 'Microinteractions',
  marquee: 'Marquee',
  ui: 'UI Motion',
  transition: 'Section Transitions',
  atmosphere: 'Atmosphere',
};

export const skillsByCategory = motionSkills.reduce<Record<string, MotionSkill[]>>((acc, s) => {
  (acc[s.category] ??= []).push(s);
  return acc;
}, {});
