import type { MotionSkill, MotionCategory } from '@/motion/core/types';

/**
 * THE SKILL REGISTRY.
 *
 * One entry per reusable behaviour in the system. The showcase reads this file
 * to build its documentation cards and its inspector, so a skill that is not
 * registered here is invisible — deliberately. Adding a skill and registering
 * it are the same task.
 *
 * `sourceReference` quotes the reference brief verbatim; MOTION-SOURCE-MAP.md
 * is generated from these strings, so keep them exact.
 */
export const motionSkills: MotionSkill[] = [
  /* ── A · LOAD & TRANSITIONS ─────────────────────────────────────────── */
  {
    id: 'cinematic-loader',
    name: 'Loader cinematográfico',
    category: 'load',
    description: 'Velo a pantalla completa con el logotipo brillando y una salida suavizada.',
    sourceReference: 'Loading screen (3s monogram shimmer, ease-out fade)',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['gsap', 'react', 'css'],
    desktop: 'Aguanta 3 segundos, el monograma brilla, y sale en 0,9 s levantando la marca mientras el velo cae.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'Mismos tiempos, pero la espera es lo primero que se recorta si la carga va justa.' },
    reducedMotion: { behaviour: 'desactivado', note: 'Se quita entero, la espera incluida. Pedir menos movimiento no es pedir esperar más por él.' },
    recommendedUse: ['Webs de agencia y porfolios', 'Microsites de campaña', 'Donde el primer fotograma marca el tono'],
    export: 'CinematicLoader',
    usage: '<CinematicLoader duration={3} logo="MS" skipOnRepeatVisit />',
  },
  {
    id: 'page-reveal',
    name: 'Entrada de página',
    category: 'load',
    description: 'La entrada que sigue al loader: una subida corta y una opacidad.',
    sourceReference: 'then ease-out fade',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['gsap', 'react'],
    desktop: '14 px de subida en 1 s, arrancando cuando el loader se retira.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Solo opacidad y transform, así que no cuesta nada en ningún sitio.' },
    reducedMotion: { behaviour: 'estático', note: 'El contenido se coloca, no se anima.' },
    recommendedUse: ['Toda página que use el loader', 'Cambios de ruta'],
    export: 'PageReveal',
    usage: '<PageReveal delay={0.3}>{children}</PageReveal>',
  },

  /* ── B · HERO & CINEMATIC ───────────────────────────────────────────── */
  {
    id: 'cinematic-hero',
    name: 'Hero cinematográfico',
    category: 'hero',
    description: 'Hero a pantalla completa que compone vídeo de fondo, velo, resplandor, partículas, viñeta y grano en un orden de capas fijo.',
    sourceReference: 'Hero section (full-bleed HLS video bg, centered headline) · Hero takes 100svh',
    difficulty: 'intermedio',
    performanceCost: 'medio',
    dependencies: ['react', 'css', 'canvas', 'hls.js'],
    desktop: 'Todas las capas activas sobre un vídeo en marcha.',
    tablet: 'Todas las capas, con menos partículas.',
    mobile: { behaviour: 'simplificado', note: 'Imagen fija en vez de vídeo y un tercio de las partículas. Medido en svh para que el botón no quede bajo la barra de direcciones al llegar.' },
    reducedMotion: { behaviour: 'estático', note: 'Fotograma fijo, sin partículas y sin latido del resplandor. La composición se mantiene.' },
    recommendedUse: ['Landings de agencia', 'Lanzamientos de producto', 'Webs de campaña de marca'],
    export: 'CinematicHero',
    usage: '<CinematicHero media={{ sources }} particles grain glow>{...}</CinematicHero>',
  },
  {
    id: 'background-video',
    name: 'Vídeo de fondo (HLS)',
    category: 'hero',
    description: 'Vídeo de fondo mudo que arranca solo, con camino HLS, fuentes progresivas de respaldo y tres alternativas distintas a imagen fija.',
    sourceReference: 'Background: hls.js video with 50% black overlay',
    difficulty: 'avanzado',
    performanceCost: 'alto',
    dependencies: ['hls.js', 'react'],
    desktop: 'hls.js donde hace falta; HLS nativo en Safari, donde cargar además la librería serían dos reproductores peleando por un mismo elemento.',
    tablet: 'Igual, limitado al tamaño del reproductor.',
    mobile: { behaviour: 'estático', note: 'Imagen fija si se activa posterOnMobile. También cae a la imagen con Ahorro de datos y en 2G, por motivos distintos al del teléfono.' },
    reducedMotion: { behaviour: 'estático', note: 'Fotograma fijo. Movimiento que nadie pidió es justo lo que esa preferencia significa.' },
    recommendedUse: ['Fondos de hero', 'Fondos ambientales de sección', 'Bobinas de trabajo'],
    export: 'HlsVideo',
    usage: '<HlsVideo src="/stream.m3u8" sources={[...]} poster="/poster.jpg" pauseOffscreen />',
  },
  {
    id: 'media-overlay',
    name: 'Velo sobre el vídeo',
    category: 'hero',
    description: 'Capa configurable sobre el vídeo — plana, direccional o radial — que hace legible el texto de encima.',
    sourceReference: '50% black overlay',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['css'],
    desktop: 'Degradado direccional por defecto: oscurece solo la franja donde va el texto y deja viva el resto de la imagen.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Suele necesitar más opacidad: con menos pantalla el texto cae sobre zonas más cargadas del fotograma.' },
    reducedMotion: { behaviour: 'igual', note: 'Es estático por naturaleza.' },
    recommendedUse: ['Cualquier texto sobre vídeo o foto', 'Legibilidad del hero', 'Velos en imágenes de tarjeta'],
    export: 'MediaOverlay',
    usage: '<MediaOverlay opacity={0.5} gradient="to-bottom" />',
  },
  {
    id: 'ambient-particles',
    name: 'Partículas de polvo',
    category: 'hero',
    description: 'Motas de polvo en canvas que suben flotando, cada una respirando a su ritmo.',
    sourceReference: 'Subtle dust particle layer on top',
    difficulty: 'intermedio',
    performanceCost: 'medio',
    dependencies: ['canvas', 'react'],
    desktop: 'Unas 46 motas en una sola capa de canvas. El bucle se detiene en cuanto la capa sale de pantalla.',
    tablet: 'Igual, con menos motas.',
    mobile: { behaviour: 'simplificado', note: 'Un tercio de la cantidad, o fuera del todo con disableOnMobile.' },
    reducedMotion: { behaviour: 'desactivado', note: 'No se dibuja nada; el canvas ni siquiera se monta.' },
    recommendedUse: ['Heros cinematográficos', 'Secciones oscuras con atmósfera'],
    export: 'DustParticles',
    usage: '<DustParticles count={46} disableOnMobile />',
  },

  /* ── C · TEXT ───────────────────────────────────────────────────────── */
  {
    id: 'text-reveal',
    name: 'Aparición del titular',
    category: 'text',
    description: 'El titular entra subiendo, por líneas, por palabras, por letras o entero.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals · Headline mixing sans + italic serif',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Las líneas suben desde detrás de una máscara, escalonadas, una vez cargadas las tipografías.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'Por palabras o entero: un titular largo partido en muchas líneas tarda demasiado en una pantalla estrecha.' },
    reducedMotion: { behaviour: 'estático', note: 'No se parte nada, lo que además deja intacto el árbol de accesibilidad.' },
    recommendedUse: ['Titulares de hero', 'Aperturas de sección', 'Citas destacadas'],
    export: 'TextReveal',
    usage: '<TextReveal by="lines" stagger={0.08}>Your headline</TextReveal>',
  },
  {
    id: 'split-text-reveal',
    name: 'Partidor de texto',
    category: 'text',
    description: 'El motor que hay debajo del titular: parte el texto en trozos sin perder la etiqueta accesible.',
    sourceReference: 'Headline mixing sans + italic serif',
    difficulty: 'avanzado',
    performanceCost: 'bajo',
    dependencies: ['gsap'],
    desktop: 'Parte por letras, palabras o líneas, midiendo con las tipografías ya cargadas.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'Se evita partir por letras: decenas de trozos por titular cuestan cálculo de maquetación para poca ganancia visible.' },
    reducedMotion: { behaviour: 'desactivado', note: 'No se llega a usar.' },
    recommendedUse: ['Titulares cinematográficos', 'Tipografía en movimiento'],
    export: 'splitText',
    usage: 'const { parts, revert } = splitText(el, "lines")',
  },
  {
    id: 'fade-up',
    name: 'Entrada desde abajo',
    category: 'text',
    description: 'La entrada de siempre: opacidad más una subida corta.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: '36 px de subida en 0,8 s.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'La distancia baja a unos 16 px: un recorrido largo en una pantalla corta llega tarde.' },
    reducedMotion: { behaviour: 'estático', note: 'Visible desde el principio; no se crea ningún disparador.' },
    recommendedUse: ['Casi cualquier cosa', 'La opción por defecto si dudas'],
    export: 'FadeUp',
    usage: '<FadeUp distance={36}>{children}</FadeUp>',
  },
  {
    id: 'fade-scale',
    name: 'Entrada con escala',
    category: 'text',
    description: 'Entra asentándose del 94% al 100% mientras aparece.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Escala del 94% al 100% junto con la opacidad.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Solo transform y opacidad.' },
    reducedMotion: { behaviour: 'estático', note: 'Se coloca ya a su tamaño final.' },
    recommendedUse: ['Bloques de imagen o vídeo', 'Tarjetas', 'Logotipos'],
    export: 'FadeScale',
    usage: '<FadeScale>{children}</FadeScale>',
  },
  {
    id: 'stagger-reveal',
    name: 'Entrada escalonada',
    category: 'text',
    description: 'Los hijos entran en secuencia desde un solo disparador.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'básico',
    performanceCost: 'bajo',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: '0,08 s entre cada hijo, en el orden en que están escritos.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'Paso más corto: en una sola columna, doce elementos a 0,08 s tardan un segundo entero.' },
    reducedMotion: { behaviour: 'estático', note: 'Todos los hijos visibles a la vez.' },
    recommendedUse: ['Listas', 'Rejillas de características', 'Menús'],
    export: 'StaggerReveal',
    usage: '<StaggerReveal stagger={0.08}>{items}</StaggerReveal>',
  },
  {
    id: 'clip-reveal',
    name: 'Barrido con máscara',
    category: 'text',
    description: 'El contenido se descubre con un barrido, no con una opacidad.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['gsap', 'scrolltrigger', 'css'],
    desktop: 'Barrido vertical, horizontal o desde el centro.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'El barrido lo resuelve el compositor; no repinta nada.' },
    reducedMotion: { behaviour: 'estático', note: 'Se quita la máscara y se ve el contenido.' },
    recommendedUse: ['Imágenes', 'Separadores editoriales', 'Descubrir paneles a sangre'],
    export: 'ClipReveal',
    usage: '<ClipReveal clipFrom="bottom">{children}</ClipReveal>',
  },

  /* ── D · SCROLL ─────────────────────────────────────────────────────── */
  {
    id: 'scroll-reveal-engine',
    name: 'Motor de entradas por scroll',
    category: 'scroll',
    description: 'La única pieza por la que pasan todas las entradas: limpieza, estado inicial, movimiento reducido y marcas de depuración, resueltos una sola vez.',
    sourceReference: 'Scroll: GSAP ScrollTrigger for section reveals',
    difficulty: 'avanzado',
    performanceCost: 'bajo',
    dependencies: ['gsap', 'scrolltrigger', 'react'],
    desktop: 'Los disparadores viven dentro de su contenedor y se deshacen solos al desmontarlo.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Se ignora el cambio de alto del móvil, para que plegar la barra de direcciones no recalcule todos los disparadores.' },
    reducedMotion: { behaviour: 'desactivado', note: 'No se crea disparador; los elementos se muestran directamente.' },
    recommendedUse: ['La base de todos los demás efectos de scroll'],
    export: 'useScrollReveal',
    usage: 'const ref = useScrollReveal({ kind: "fade-up", children: ":scope > *" })',
  },
  {
    id: 'parallax',
    name: 'Parallax',
    category: 'scroll',
    description: 'Mueve un elemento a distinta velocidad que la página, en proporción a su propio tamaño.',
    sourceReference: 'Mobile: disable parallax, simplify hover states',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'El recorrido es una fracción del tamaño del elemento, así que un solo valor sirve en todas las pantallas.',
    tablet: 'Velocidad reducida.',
    mobile: { behaviour: 'desactivado', note: 'Apagado por defecto. Con un recorrido corto y el dedo en el cristal, el parallax se percibe como retraso.' },
    reducedMotion: { behaviour: 'desactivado', note: 'No se crea la animación.' },
    recommendedUse: ['Imágenes de hero', 'Secciones editoriales', 'Fondos por capas'],
    export: 'useParallax',
    usage: 'const ref = useParallax({ speed: 0.18 })',
  },
  {
    id: 'sticky-story',
    name: 'Relato anclado',
    category: 'scroll',
    description: 'La sección se ancla y va pasando capítulos, moviendo texto e imagen desde un mismo valor de avance.',
    sourceReference: 'Sticky-pinned scroll variant on desktop',
    difficulty: 'avanzado',
    performanceCost: 'medio',
    dependencies: ['gsap', 'scrolltrigger', 'react'],
    desktop: 'La sección se ancla y los capítulos se funden en el sitio, con una barra de avance.',
    tablet: 'Anclada, con menos recorrido por capítulo.',
    mobile: { behaviour: 'simplificado', note: 'Una maqueta distinta, no una más pequeña: los capítulos se apilan y se recorren normal, porque anclar pelea con la barra del navegador en el móvil.' },
    reducedMotion: { behaviour: 'simplificado', note: 'Pasa a la maqueta apilada.' },
    recommendedUse: ['Secciones de proceso o método', 'Casos de estudio', 'Recorridos por funcionalidades'],
    export: 'StickyStory',
    usage: '<StickyStory chapters={chapters} heightPerStep={1} />',
  },
  {
    id: 'horizontal-scroll',
    name: 'Scroll horizontal',
    category: 'scroll',
    description: 'El scroll vertical mueve una tira lateral mientras la sección está anclada.',
    sourceReference: 'Sticky-pinned scroll variant on desktop',
    difficulty: 'avanzado',
    performanceCost: 'medio',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'La distancia se calcula del ancho real de la tira y se recalcula al recargar medidas.',
    tablet: 'Igual, con una tira más corta.',
    mobile: { behaviour: 'simplificado', note: 'Tira deslizable nativa con imán y contención, para que pasarse del final no dispare el gesto de volver atrás.' },
    reducedMotion: { behaviour: 'simplificado', note: 'Tira deslizable normal.' },
    recommendedUse: ['Galerías de porfolio', 'Líneas de tiempo', 'Gamas de producto'],
    export: 'HorizontalScrollSection',
    usage: '<HorizontalScrollSection>{cards}</HorizontalScrollSection>',
  },
  {
    id: 'scroll-scrub-media',
    name: 'Vídeo recorrido por scroll',
    category: 'scroll',
    description: 'Vídeo o secuencia de imágenes cuyo fotograma lo elige la posición del scroll.',
    sourceReference: 'Sticky-pinned scroll variant on desktop',
    difficulty: 'avanzado',
    performanceCost: 'alto',
    dependencies: ['gsap', 'scrolltrigger', 'canvas'],
    desktop: 'Busca el fotograma dentro del ciclo de dibujado, nunca más rápido de lo que el decodificador entrega.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'Clips más cortos o menos fotogramas. Necesita un servidor que responda peticiones Range o no se puede recorrer.' },
    reducedMotion: { behaviour: 'estático', note: 'Se queda en el primer fotograma.' },
    recommendedUse: ['Presentaciones de producto', 'Antes y después', 'Vídeos de montaje o de proceso'],
    export: 'useScrollScrubVideo',
    usage: 'const { containerRef, videoRef } = useScrollScrubVideo()',
  },

  /* ── E · PRODUCT ────────────────────────────────────────────────────── */
  {
    id: 'product-scroll',
    name: 'Producto por scroll',
    category: 'product',
    description: 'Escenario de producto anclado, con capítulos y anotaciones sincronizados, sobre vídeo, secuencia de imágenes o dibujo por canvas.',
    sourceReference: 'Sticky-pinned scroll variant on desktop · scroll-controlled',
    difficulty: 'avanzado',
    performanceCost: 'alto',
    dependencies: ['gsap', 'scrolltrigger', 'canvas', 'hls.js', 'react'],
    desktop: 'Tres fuentes intercambiables tras una misma interfaz; capítulos, anotaciones y barra de avance leen el mismo valor.',
    tablet: 'Anclado, con menos recorrido.',
    mobile: { behaviour: 'simplificado', note: 'Pasa a una maqueta apilada. Un producto a 375 px de ancho con un texto encima no hay quien lo lea.' },
    reducedMotion: { behaviour: 'simplificado', note: 'Maqueta apilada; solo el primer fotograma.' },
    recommendedUse: ['Contar un producto', 'Webs de industria y maquinaria', 'Escaparates de render 3D'],
    export: 'ProductScroll',
    usage: '<ProductScroll source={{ type: "canvas", render }} chapters={...} hotspots={...} />',
  },

  {
    id: 'objeto-en-viaje',
    name: 'Objeto en viaje',
    category: 'product',
    description: 'Un objeto 3D dibujado en un lienzo fijo detrás de TODA la página, que se monta, se cierra y se envuelve mientras el lector recorre las secciones.',
    sourceReference: 'Sticky-pinned scroll variant on desktop · scroll-controlled',
    difficulty: 'avanzado',
    performanceCost: 'medio',
    dependencies: ['gsap', 'scrolltrigger', 'canvas'],
    desktop: 'Un único valor de avance va del primer píxel al último del documento. El objeto no pertenece a ninguna sección: las atraviesa, cambiando de lado para no pisar nunca la columna de texto.',
    tablet: 'Igual, con menos recorrido lateral.',
    mobile: { behaviour: 'simplificado', note: 'El objeto se sale de la coreografía y se atraca centrado en la banda de arriba. A 390px, uno que cruza de lado a lado pasa la mitad del tiempo fuera de pantalla y se pelea con cada párrafo.' },
    reducedMotion: { behaviour: 'estático', note: 'Se dibuja una vez, terminado y envuelto. Se quita el viaje, no el producto.' },
    recommendedUse: ['Contar un producto que se fabrica por pasos', 'Webs de industria', 'Cuando la página tiene que leerse como una sola escena'],
    export: 'dibujarViaje',
    usage: 'Ver src/viaje/ · demo en /motion/viaje.html',
  },

  /* ── F · CARDS ──────────────────────────────────────────────────────── */
  {
    id: 'card-hover-lift',
    name: 'Tarjeta que se eleva',
    category: 'cards',
    description: 'La tarjeta sube hacia quien mira al pasar el cursor.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['framer-motion'],
    desktop: '6 px de subida en 300 ms.',
    tablet: 'Igual allí donde hay puntero.',
    mobile: { behaviour: 'desactivado', note: 'Ni se instala el detector. Un efecto de cursor que se dispara al tocar hace que la tarjeta parezca rota justo antes de navegar.' },
    reducedMotion: { behaviour: 'desactivado', note: 'Solo cambio de color.' },
    recommendedUse: ['Rejillas bento', 'Tarjetas de caso', 'Tablas de precios'],
    export: 'HoverCard',
    usage: '<HoverCard lift={6}>{content}</HoverCard>',
  },
  {
    id: 'card-scale',
    name: 'Tarjeta que crece',
    category: 'cards',
    description: 'Un crecimiento mínimo al pasar el cursor, combinable con la elevación.',
    sourceReference: 'button slight scale (1.02)',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['framer-motion'],
    desktop: 'Entre el 101% y el 103%. Más que eso se lee como otra tarjeta, no como la misma respondiendo.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'desactivado', note: 'En el móvil no existe el estado de cursor encima.' },
    reducedMotion: { behaviour: 'desactivado', note: 'Apagado.' },
    recommendedUse: ['Tarjetas de característica', 'Mosaicos de imagen'],
    export: 'HoverCard',
    usage: '<HoverCard scale={1.02} lift={0} />',
  },
  {
    id: 'image-zoom',
    name: 'Zoom de imagen',
    category: 'cards',
    description: 'La imagen crece dentro de un marco fijo, y el marco no se mueve.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['framer-motion', 'css'],
    desktop: 'Crece un 6% en 700 ms dentro de un marco que recorta.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'desactivado', note: 'En el móvil no existe el estado de cursor encima.' },
    reducedMotion: { behaviour: 'desactivado', note: 'Imagen quieta.' },
    recommendedUse: ['Miniaturas de porfolio', 'Tarjetas editoriales', 'Fichas de producto'],
    export: 'ZoomImage',
    usage: '<ZoomImage src="/shot.jpg" scale={1.06} />',
  },
  {
    id: 'glass-card',
    name: 'Tarjeta de cristal',
    category: 'cards',
    description: 'Superficie translúcida y desenfocada, con borde de un píxel y un brillo en el canto superior.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'básico',
    performanceCost: 'medio',
    dependencies: ['css'],
    desktop: 'Desenfoque del fondo con algo de saturación, más el brillo del canto que la hace leerse como cristal.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'Bajar el radio de desenfoque. Es la propiedad más cara de toda la librería en la gráfica de un móvil.' },
    reducedMotion: { behaviour: 'igual', note: 'Superficie estática.' },
    recommendedUse: ['Tarjetas sobre fotografía', 'Paneles flotantes', 'Barras de navegación'],
    export: 'GlassCard',
    usage: '<GlassCard radius={16}>{content}</GlassCard>',
  },
  {
    id: 'bento-grid-motion',
    name: 'Entrada de rejilla bento',
    category: 'cards',
    description: 'Entrada escalonada para una rejilla asimétrica, en orden de lectura.',
    sourceReference: '8 cards in an asymmetric grid',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Las tarjetas suben en orden de lectura, con 0,07 s entre cada una.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'La rejilla pasa a una columna, donde el orden de lectura y el visual ya coinciden.' },
    reducedMotion: { behaviour: 'estático', note: 'Todas las tarjetas visibles.' },
    recommendedUse: ['Rejillas de características', 'Resúmenes de servicios', 'Paneles de control'],
    export: 'BentoGrid',
    usage: '<BentoGrid stagger={0.07}>{cards}</BentoGrid>',
  },

  /* ── G · MICROINTERACTIONS ──────────────────────────────────────────── */
  {
    id: 'button-scale',
    name: 'Botón que responde',
    category: 'interaction',
    description: 'Respuesta al cursor y a la pulsación: 102% y 98%.',
    sourceReference: 'button slight scale (1.02)',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['framer-motion'],
    desktop: '102% con el cursor encima, 98% al pulsar, en 200 ms.',
    tablet: 'Solo el estado de pulsación.',
    mobile: { behaviour: 'simplificado', note: 'La respuesta al pulsar se mantiene; la del cursor no existe.' },
    reducedMotion: { behaviour: 'desactivado', note: 'Solo transición de color.' },
    recommendedUse: ['Todos los botones del sistema'],
    export: 'MagneticButton',
    usage: '<MagneticButton variant="solid">Start</MagneticButton>',
  },
  {
    id: 'magnetic-button',
    name: 'Botón magnético',
    category: 'interaction',
    description: 'El botón se inclina hacia el cursor dentro de un radio y vuelve al salir.',
    sourceReference: 'Hover: card lift, button slight scale (1.02)',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['gsap', 'framer-motion'],
    desktop: 'El detector vive en el propio botón y reapunta una sola animación viva, en vez de crear una por cada movimiento del ratón.',
    tablet: 'Apagado salvo que haya un puntero fino.',
    mobile: { behaviour: 'desactivado', note: 'Ni se instala el detector. No hay cursor al que atraerse.' },
    reducedMotion: { behaviour: 'desactivado', note: 'Un botón normal.' },
    recommendedUse: ['Botones principales', 'Acciones del hero'],
    export: 'MagneticButton',
    usage: '<MagneticButton strength={0.35} radius={60}>Talk to us</MagneticButton>',
  },
  {
    id: 'magnetic-link',
    name: 'Enlace magnético',
    category: 'interaction',
    description: 'La misma atracción, más floja y sin crecer, para enlaces dentro del texto.',
    sourceReference: 'Hover: card lift, button slight scale (1.02)',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['gsap'],
    desktop: 'Fuerza 0,22 y radio 34 px, sin escala: un enlace que crece compite con su propio párrafo.',
    tablet: 'Apagado con puntero grueso.',
    mobile: { behaviour: 'desactivado', note: 'Un enlace normal.' },
    reducedMotion: { behaviour: 'desactivado', note: 'Un enlace normal.' },
    recommendedUse: ['Menú del pie', 'Énfasis dentro del texto', 'Elementos de menú'],
    export: 'MagneticLink',
    usage: '<MagneticLink href="/work">Selected work</MagneticLink>',
  },
  {
    id: 'hover-glow',
    name: 'Resplandor que sigue al cursor',
    category: 'interaction',
    description: 'Un halo de luz que persigue al cursor por la superficie.',
    sourceReference: 'Background: subtle radial lime glow at bottom-center',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['css', 'react'],
    desktop: 'Dos variables de CSS alimentan un único degradado fijo, así que no se reconstruye el degradado en cada movimiento.',
    tablet: 'Resplandor fijo y centrado.',
    mobile: { behaviour: 'simplificado', note: 'Resplandor fijo y centrado a media intensidad, para que la superficie siga leyéndose iluminada.' },
    reducedMotion: { behaviour: 'simplificado', note: 'Resplandor fijo y centrado.' },
    recommendedUse: ['Tarjetas', 'Paneles', 'Zonas de llamada a la acción'],
    export: 'useHoverGlow',
    usage: 'const ref = useHoverGlow({ size: 320 })',
  },
  {
    id: 'image-tilt',
    name: 'Inclinación 3D',
    category: 'interaction',
    description: 'La superficie se inclina hacia el cursor, con tope en unos 7 grados.',
    sourceReference: 'Hover: card lift, button slight scale (1.02)',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['gsap'],
    desktop: 'El eje vertical sigue al horizontal y el horizontal se invierte: eso es lo que hace que parezca empujada y no dirigida.',
    tablet: 'Apagado con puntero grueso.',
    mobile: { behaviour: 'desactivado', note: 'No se instala el detector.' },
    reducedMotion: { behaviour: 'desactivado', note: 'Superficie plana.' },
    recommendedUse: ['Tarjetas de característica', 'Product thumbnails', 'Retratos de equipo'],
    export: 'useTilt',
    usage: 'const ref = useTilt({ max: 7 })',
  },

  /* ── H · MARQUEE ────────────────────────────────────────────────────── */
  {
    id: 'infinite-marquee',
    name: 'Tira infinita',
    category: 'marquee',
    description: 'Tira que gira sin costura, en CSS puro, y se para al pasar el cursor.',
    sourceReference: 'Marquee: CSS infinite scroll, pauses on hover · BUILT WITH AI · NOT BY AI ·',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['css', 'react'],
    desktop: 'La tira se duplica exactamente una vez y se desplaza la mitad; la copia se oculta a los lectores de pantalla para que no se lea dos veces.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Lo resuelve el compositor fuera del hilo principal: de los pocos efectos que no cuestan nada en un móvil.' },
    reducedMotion: { behaviour: 'estático', note: 'Se convierte en una tira que se desliza a mano. Las palabras eran lo importante; el movimiento era adorno.' },
    recommendedUse: ['Logotipos de clientes', 'Tiras de mensaje', 'Listas de servicios'],
    export: 'Tira infinita',
    usage: '<Marquee speed={26} reverse pauseOnHover>{items}</Marquee>',
  },

  /* ── I · UI MOTION ──────────────────────────────────────────────────── */
  {
    id: 'animated-accordion',
    name: 'Acordeón animado',
    category: 'ui',
    description: 'Los paneles abren y cierran con altura y opacidad, con teclado y accesibilidad completos.',
    sourceReference: 'FAQ accordion · Smooth height + opacity transition (300ms ease-out)',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['framer-motion', 'react'],
    desktop: '300 ms midiendo la altura real, en modo de uno abierto o varios.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Mismo comportamiento, con zonas de toque más grandes.' },
    reducedMotion: { behaviour: 'simplificado', note: 'Abre y cierra al instante; el cambio de estado se sigue viendo.' },
    recommendedUse: ['FAQ', 'Fichas técnicas', 'Información que se despliega a demanda'],
    export: 'Accordion',
    usage: '<Accordion items={faq} mode="single" />',
  },

  /* ── J · SECTION TRANSITIONS ────────────────────────────────────────── */
  {
    id: 'fade-section-transition',
    name: 'Sección que aparece',
    category: 'transition',
    description: 'La sección aparece al entrar en pantalla.',
    sourceReference: 'then ease-out fade',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: '1,2 s de opacidad.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Solo opacidad.' },
    reducedMotion: { behaviour: 'estático', note: 'Visible desde el principio.' },
    recommendedUse: ['La entrada de sección por defecto'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="fade">{section}</SectionTransition>',
  },
  {
    id: 'scale-section-transition',
    name: 'Sección que se asienta',
    category: 'transition',
    description: 'La sección se asienta del 106% al 100%.',
    sourceReference: 'then ease-out fade',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['gsap', 'scrolltrigger'],
    desktop: 'Escala junto con la opacidad.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Transform only.' },
    reducedMotion: { behaviour: 'estático', note: 'Se coloca ya a su tamaño final.' },
    recommendedUse: ['Secciones dominadas por imagen', 'Paneles a sangre'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="scale" />',
  },
  {
    id: 'clip-section-transition',
    name: 'Sección que se descubre',
    category: 'transition',
    description: 'La sección se descubre desde un recuadro redondeado hasta ocupar todo el ancho.',
    sourceReference: 'then ease-out fade',
    difficulty: 'intermedio',
    performanceCost: 'bajo',
    dependencies: ['gsap', 'scrolltrigger', 'css'],
    desktop: 'Máscara que se abre, con las esquinas redondeándose en el camino.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Lo resuelve el compositor.' },
    reducedMotion: { behaviour: 'estático', note: 'Se quita la máscara.' },
    recommendedUse: ['El paso del hero al contenido', 'Cortes de capítulo'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="clip" />',
  },
  {
    id: 'blur-transition',
    name: 'Sección que enfoca',
    category: 'transition',
    description: 'La sección pasa de desenfocada a nítida.',
    sourceReference: 'then ease-out fade',
    difficulty: 'intermedio',
    performanceCost: 'alto',
    dependencies: ['gsap', 'scrolltrigger', 'css'],
    desktop: 'De 14 px de desenfoque a cero.',
    tablet: 'Con menos radio.',
    mobile: { behaviour: 'simplificado', note: 'Mejor usar la aparición simple. El desenfoque repinta todo el bloque en cada fotograma: aceptable como entrada corta, caro si se recorre con el scroll.' },
    reducedMotion: { behaviour: 'estático', note: 'Nítida desde el principio.' },
    recommendedUse: ['Un único paso desde el hero', 'Con mucha moderación'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="blur" />',
  },
  {
    id: 'cinematic-section-transition',
    name: 'Transición cinematográfica',
    category: 'transition',
    description: 'Máscara, escala y desenfoque compuestos en una sola entrada de autor.',
    sourceReference: 'then ease-out fade',
    difficulty: 'avanzado',
    performanceCost: 'alto',
    dependencies: ['gsap', 'scrolltrigger', 'css'],
    desktop: '1,6 s y tres propiedades a la vez.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'Se queda sin el desenfoque.' },
    reducedMotion: { behaviour: 'estático', note: 'El contenido se coloca sin más.' },
    recommendedUse: ['Un solo momento por página: donde el relato gira'],
    export: 'SectionTransition',
    usage: '<SectionTransition kind="cinematic" />',
  },

  /* ── K · ATMOSPHERE ─────────────────────────────────────────────────── */
  {
    id: 'grain',
    name: 'Grano de película',
    category: 'atmosphere',
    description: 'Textura de película sobre la interfaz, a saltos y no suave.',
    sourceReference: 'Subtle dust particle layer on top',
    difficulty: 'básico',
    performanceCost: 'bajo',
    dependencies: ['css'],
    desktop: 'Un mosaico de ruido en SVG, dibujado una vez y repetido.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'Se quita la animación y se queda la textura.' },
    reducedMotion: { behaviour: 'estático', note: 'Textura sin el titileo.' },
    recommendedUse: ['Interfaces oscuras', 'Heros cinematográficos', 'Webs dominadas por fotografía'],
    export: 'Grain',
    usage: '<Grain opacity={0.045} animated />',
  },
  {
    id: 'radial-glow',
    name: 'Resplandor de fondo',
    category: 'atmosphere',
    description: 'Un foco de luz de color, anclado donde haga falta dentro de una sección.',
    sourceReference: 'Background: subtle radial lime glow at bottom-center',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['css'],
    desktop: 'Posición, tamaño, color e intensidad configurables, con un latido opcional de 9 s.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Un degradado no cuesta nada.' },
    reducedMotion: { behaviour: 'estático', note: 'Se quita el latido; el resplandor se queda.' },
    recommendedUse: ['Fondos de hero', 'Secciones de cierre', 'Anclar el color de acento'],
    export: 'RadialGlow',
    usage: '<RadialGlow x="50%" y="100%" color="rgba(200,242,74,0.3)" animated />',
  },
  {
    id: 'vignette',
    name: 'Viñeta',
    category: 'atmosphere',
    description: 'Oscurece los bordes para que el ojo se pose en el centro.',
    sourceReference: '50% black overlay',
    difficulty: 'básico',
    performanceCost: 'nulo',
    dependencies: ['css'],
    desktop: 'Degradado elíptico, con intensidad y extensión configurables.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Gratis.' },
    reducedMotion: { behaviour: 'igual', note: 'Estática.' },
    recommendedUse: ['Sobre vídeo', 'Imagen a sangre', 'Encuadre cinematográfico'],
    export: 'Viñeta',
    usage: '<Vignette intensity={0.55} spread={0.55} />',
  },
  {
    id: 'light-sweep',
    name: 'Barrido de luz',
    category: 'atmosphere',
    description: 'Una banda de brillo que cruza la superficie, al pasar el cursor o en bucle.',
    sourceReference: 'Loading screen (3s monogram shimmer, ease-out fade)',
    difficulty: 'básico',
    performanceCost: 'bajo',
    dependencies: ['css'],
    desktop: 'Solo mueve un degradado: compone, no repinta.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'simplificado', note: 'El modo por cursor nunca se dispara; usar el modo en bucle o quitarlo.' },
    reducedMotion: { behaviour: 'desactivado', note: 'No dibuja nada.' },
    recommendedUse: ['Botones', 'Tarjetas', 'Logotipos'],
    export: 'LightSweep',
    usage: '<LightSweep onHover speed={3.2} />',
  },
  {
    id: 'ambient-blur',
    name: 'Desenfoque de fondo',
    category: 'atmosphere',
    description: 'Un plano esmerilado sobre lo que haya detrás.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'básico',
    performanceCost: 'alto',
    dependencies: ['css'],
    desktop: 'Desenfoque y saturación del fondo, con un tinte encima.',
    tablet: 'Con menos radio.',
    mobile: { behaviour: 'simplificado', note: 'Bajar el radio a la mitad o cambiarlo por un tinte opaco. Es la propiedad más cara de la librería.' },
    reducedMotion: { behaviour: 'igual', note: 'Estática.' },
    recommendedUse: ['Menús que se quedan pegados', 'Fondos de ventana modal', 'Paneles superpuestos'],
    export: 'AmbientBlur',
    usage: '<AmbientBlur blur={24} tint="rgba(8,9,10,0.45)" />',
  },
  {
    id: 'gradient-border',
    name: 'Borde degradado',
    category: 'atmosphere',
    description: 'Un filo degradado alrededor de la superficie, enmascarado para que el cristal de debajo sobreviva.',
    sourceReference: 'Each card: rounded 16px, glass surface, hover lift 6px',
    difficulty: 'intermedio',
    performanceCost: 'nulo',
    dependencies: ['css'],
    desktop: 'La máscara pinta solo el aro, así que el desenfoque de debajo sigue funcionando.',
    tablet: 'Igual que en escritorio.',
    mobile: { behaviour: 'igual', note: 'Gratis.' },
    reducedMotion: { behaviour: 'igual', note: 'Estática.' },
    recommendedUse: ['Tarjetas destacadas', 'Planes destacados', 'Estados activos'],
    export: 'GradientBorder',
    usage: '<GradientBorder radius={16}>{content}</GradientBorder>',
  },
];

export const skillsById = Object.fromEntries(motionSkills.map((s) => [s.id, s])) as Record<string, MotionSkill>;

export const categoryLabels: Record<MotionCategory, string> = {
  load: 'Carga y transiciones',
  hero: 'Hero y cine',
  text: 'Movimiento de texto',
  scroll: 'Movimiento por scroll',
  product: 'Experiencia de producto',
  cards: 'Tarjetas y bento',
  interaction: 'Microinteracciones',
  marquee: 'Tira infinita',
  ui: 'Movimiento de interfaz',
  transition: 'Transiciones de sección',
  atmosphere: 'Atmósfera',
};

export const skillsByCategory = motionSkills.reduce<Record<string, MotionSkill[]>>((acc, s) => {
  (acc[s.category] ??= []).push(s);
  return acc;
}, {});
